name: Linter

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    name: Run Linter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: CodeQuality
        uses: JacobDomagala/StaticAnalysis@112-support-python
        with:
          language: "Python"
          verbose: True
          pylint_args: "--rcfile=setup.cfg --max-line-length=120 --max-locals=25 --min-similarity-lines=10"

      - name: PyLint
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "src test"
          use-pylint: true
          use-pycodestyle: true
          use-flake8: true
          use-black: true
          use-mypy: true
          use-isort: false
          extra-pylint-options: "--rcfile=setup.cfg --max-line-length=120 --max-locals=25 --min-similarity-lines=10"
          extra-mypy-options: "--ignore-missing-imports --show-error-codes"
          extra-flake8-options: "--max-line-length=120 --ignore=E203,E402"
          extra-pycodestyle-options: "--max-line-length=120 --ignore=E203,E402"


